### ISSUE TITLE
The term 'which' is not recognized

### ISSUE THREAD

**Issue by Gl00ria** [ConnorSweeneyDev/Windows11Workflow#1]
Appreciate this fantastic workflow,
I am having the following error despite the fact everything is correct as I followed the instructions on the `README`

```
which : The term 'which' is not recognized as the name of a cmdlet, function, script file, or operable program. Check
the spelling of the name, or if a path was included, verify that the path is correct and try again.
At C:\Users\[USERNAME]\Documents\PowerShell\Microsoft.PowerShell_profile.ps1:13 char:9
+     cd (which)
+         ~~~~~
    + CategoryInfo          : ObjectNotFound: (which:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
```
Looking forward to hearing your response,

**Comment by ConnorSweeneyDev** [comment]
it looks like you havent changed the path to the actual location, the error
you've provided shows the path "C:/Users/[USERNAME]/Doc... " - you need to
change [USERNAME] to the name your pc knows you as

**Comment by ConnorSweeneyDev** [comment]
> Thanks for your response, I have the path set up correctly to my username

see my edit to the reply if the issue persists

**Comment by ConnorSweeneyDev** [comment]
Do you also have the folder `C:/which` ? Or just `C:/scripts/which` ?

Either way, if you change that line from `cd (which)` to `cd (C:/scripts/which/which.bat)` i think your issue will be resolved.

**Comment by Gl00ria** [comment]
that fixed it, now I am having another issue invalid `preview window option: ~3` which is related to FZF. Can be found [in this line](https://github.com/ConnorSweeneyDev/Windows11Workflow/blob/eaffb3b6d25308667d69289100cb08757de7cce9/scripts/which/which.bat#L3), so I removed this  `--preview-window "~3`"

**Comment by ConnorSweeneyDev** [comment]
> now I am having another issue invalid `preview window option: ~3` which is related to FZF. Can be found [in this line](https://github.com/ConnorSweeneyDev/Windows11Workflow/blob/eaffb3b6d25308667d69289100cb08757de7cce9/scripts/which/which.bat#L3), so I removed this `--preview-window "~3`"

I had a friend who had the same issue, thankfully removing the line just works but im not sure why it works for some and not for others, might just remove it all together
