### ISSUE TITLE
Running "!ls" from neovim prints weird text

### ISSUE THREAD

**Issue by AmerM137** [ConnorSweeneyDev/Windows11Workflow#2]
Hi there,

Thanks for posting this config, it's awesome! I already yanked a few parts for my own config.

I am having a little issue with powershell, however. I copy pasted the exact parts from 

```lua
~/nvim/lua/connor/set.lua

vim.opt.shell = 'pwsh.exe'
vim.opt.shellcmdflag =
  '-NoLogo -ExecutionPolicy RemoteSigned -Command [Console]::InputEncoding=[Console]::OutputEncoding=[System.Text.Encoding]::UTF8;'
vim.opt.shellredir = '2>&1 | Out-File -Encoding UTF8 %s; exit $LastExitCode'
vim.opt.shellpipe = '2>&1 | Out-File -Encoding UTF8 %s; exit $LastExitCode'
vim.opt.shellquote = ''
vim.opt.shellxquote = ''
```

Here is the output of "!ls": 
<img width="634" alt="Screenshot 2024-07-03 214117" src="https://github.com/ConnorSweeneyDev/Windows11Workflow/assets/37887075/1a9cb6fc-a29a-4829-a769-a2e1ac7d1972">

I was googling around and it seems that these are ansi/escape/color codes that pwsh might be sending out that nvim doesn't understand? Any ideas how to fix this?

I am on Nvim 0.10.0, PowerShell 7.4.3.

**Comment by ConnorSweeneyDev** [comment]
Yes you are correct that these are the ansi escape codes for the colors that the output of ls on powershell uses.
Unfortunately, I have the same problem with these lines in the config, I have tried to fix it but really cant figure it out, however there are very few commands that actually produce this output.

For the most part, I never need to execute a command inside of neovim that produces ansi escape codes, so if you also can't fix this I would recommend using it in your config for a while and seeing if it bothers you at all, because it is really useful to have your native nvim shell be pwsh.

If you end up stumbling upon a fix at any point please let me know here, I'll keep the issue open for now.

**Comment by AmerM137** [comment]
Yes that works but it's tedious to always append Out-String to each command. I am sure there is a way to make it part of the shellcmdflag, but I think for now I found a better solution, we just need to add a " $PSStyle.OutputRendering = 'PlainText';" to the end.

New cmdshellflag:

```lua
vim.opt.cmdshellflag = 
  "-NoLogo -NoProfile -ExecutionPolicy RemoteSigned -Command [Console]::InputEncoding=[Console]::OutputEncoding=[System.Text.Encoding]::UTF8; $PSStyle.OutputRendering = 'PlainText';"
```

Resources:
See $PSSTYLE section about OutputRendering -> https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_ansi_terminals?view=powershell-7.4#redirecting-output-in-host-mode

https://www.reddit.com/r/neovim/comments/18ynho9/weird_output_when_running_external_commands_with/

https://stackoverflow.com/questions/76496274/is-neovims-command-mode-compatible-with-ansi-color-codes-output-by-shell-if-ye/77254808#77254808

discussion in Neovim repo https://github.com/neovim/neovim/issues/2765

Notes:

Looking at some of the discussions in the Neovim repo, it sounds like ```lua :te``` might work better for rich output. It's a little different than ```!``` as it opens an interactive terminal instead window (need to go into insert mode then press any key to exit). I do like it however as I prefer the full screen output. I also tend to work in the Python/IPython quite a bit so it's nice to be able to run a python program with the ```:te python somefile.py arg1 arg2``` command and it will keep the session alive if it's an interactive process.

**Comment by ConnorSweeneyDev** [comment]
One more thing to add, and I'm closing this issue now - below is the full line I will be committing:

`vim.opt.shellcmdflag = "-NoLogo -ExecutionPolicy RemoteSigned -Command [Console]::InputEncoding=[Console]::OutputEncoding=[System.Text.Encoding]::UTF8;$PSStyle.Formatting.Error = '';$PSStyle.Formatting.ErrorAccent = '';$PSStyle.Formatting.Warning = ''$PSStyle.OutputRendering = 'PlainText';"`

This sets the children of `Formatting` to have escape sequences that are empty strings - for some reason `PlainText` doesn't apply to errors and warnings, with these extra flags it is fixed.
